<?php
/**
 * MW WP Form Validation Merger
 *
 * Merges MW WP Form validation arrays into Form Plant fields.
 *
 * MW v5.1.2 storage format:
 *   [
 *     ['target' => 'お名前',  'noempty' => 1, 'between' => ['min' => 1, 'max' => 100]],
 *     ['target' => 'メール',  'noempty' => 1, 'mail' => 1],
 *     ['target' => 'file',    'fileSize' => ['bytes' => 1000000], 'fileType' => ['types' => 'jpg,png']],
 *   ]
 *
 * @package Form_Plant
 * @since   1.2.0
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Class FPLANT_MWWPForm_Validation_Merger
 *
 * @since 1.2.0
 */
class FPLANT_MWWPForm_Validation_Merger {

	/**
	 * Name translator for converting MW WP Form target names to Form Plant field names.
	 *
	 * @var FPLANT_Name_Translator
	 */
	private $translator;

	/**
	 * Logger for collecting warnings.
	 *
	 * @var FPLANT_Migrator_Base
	 */
	private $logger;

	/**
	 * Constructor.
	 *
	 * @param FPLANT_Name_Translator $translator Name translator.
	 * @param FPLANT_Migrator_Base   $logger     Logger for collecting warnings.
	 */
	public function __construct( FPLANT_Name_Translator $translator, FPLANT_Migrator_Base $logger ) {
		$this->translator = $translator;
		$this->logger     = $logger;
	}

	/**
	 * Merges validation settings into a Form Plant field array.
	 *
	 * @param array $fields            Form Plant field array generated by Field_Mapper.
	 * @param array $mw_validation     MW WP Form validation array (list of associative arrays).
	 * @return array Updated $fields.
	 */
	public function merge( array $fields, array $mw_validation ) {
		if ( empty( $mw_validation ) ) {
			return $fields;
		}

		$by_name = array();
		foreach ( $fields as $idx => $field ) {
			if ( isset( $field['name'] ) ) {
				$by_name[ $field['name'] ] = $idx;
			}
		}

		foreach ( $mw_validation as $entry ) {
			if ( ! is_array( $entry ) || empty( $entry['target'] ) ) {
				$this->logger->add_warning(
					FPLANT_Migrator_Base::LEVEL_WARNING,
					'unknown_validation_entry',
					__( 'An unknown validation entry was detected and skipped. Please check it manually in MW WP Form.', 'form-plant' )
				);
				continue;
			}

			$target_original   = (string) $entry['target'];
			$target_translated = $this->translator->translate( $target_original );

			if ( ! isset( $by_name[ $target_translated ] ) ) {
				$this->logger->add_warning(
					FPLANT_Migrator_Base::LEVEL_INFO,
					'validation_target_missing',
					sprintf(
						/* translators: %s: target field name. */
						__( 'The validation target field "%s" was not found in the form and has been skipped.', 'form-plant' ),
						$target_original
					),
					array( 'target' => $target_original )
				);
				continue;
			}

			$idx                = $by_name[ $target_translated ];
			$fields[ $idx ]     = $this->apply_rules( $fields[ $idx ], $entry, $target_original );
		}

		return $fields;
	}

	/**
	 * Applies validation rules to a single field.
	 *
	 * @param array  $field           Form Plant field array.
	 * @param array  $rules           MW WP Form validation entry.
	 * @param string $target_original Original target name (used in warnings).
	 * @return array Updated field.
	 */
	private function apply_rules( array $field, array $rules, $target_original ) {
		foreach ( $rules as $rule_key => $rule_value ) {
			if ( 'target' === $rule_key ) {
				continue;
			}

			switch ( $rule_key ) {
				case 'noempty':
				case 'required':
					$field['required'] = true;
					break;

				case 'mail':
					if ( 'email' !== $field['type'] ) {
						$field['type'] = 'email';
					}
					break;

				case 'numeric':
					if ( 'number' !== $field['type'] ) {
						$field['type'] = 'number';
					}
					break;

				case 'zip':
					if ( 'postal_code' !== $field['type'] ) {
						$field['type']          = 'postal_code';
						$field['postal_format'] = 'single';
					}
					break;

				case 'tel':
					if ( 'tel' !== $field['type'] ) {
						$field['type'] = 'tel';
					}
					break;

				case 'url':
					if ( 'url' !== $field['type'] ) {
						$field['type'] = 'url';
					}
					break;

				case 'date':
					if ( 'date' !== $field['type'] ) {
						$field['type']   = 'date';
						$field['format'] = 'Y-m-d';
					}
					break;

				case 'alpha':
					$field['validation']['pattern']         = '/^[a-zA-Z]+$/';
					$field['validation']['pattern_message'] = __( 'Please enter half-width letters only.', 'form-plant' );
					break;

				case 'alphanumeric':
					$field['validation']['pattern']         = '/^[a-zA-Z0-9]+$/';
					$field['validation']['pattern_message'] = __( 'Please enter half-width alphanumeric characters only.', 'form-plant' );
					break;

				case 'katakana':
					if ( 'name_kana' === $field['type'] ) {
						$field['kana_validation'] = 'katakana';
					} else {
						$field['validation']['pattern']         = '/^[\p{Katakana}\x{30FC}\s]+$/u';
						$field['validation']['pattern_message'] = __( 'Please enter katakana characters.', 'form-plant' );
					}
					break;

				case 'hiragana':
					if ( 'name_kana' === $field['type'] ) {
						$field['kana_validation'] = 'hiragana';
					} else {
						$field['validation']['pattern']         = '/^[\p{Hiragana}\x{30FC}\s]+$/u';
						$field['validation']['pattern_message'] = __( 'Please enter hiragana characters.', 'form-plant' );
					}
					break;

				case 'kana':
					$field['validation']['pattern']         = '/^[\p{Katakana}\p{Hiragana}\x{30FC}\s]+$/u';
					$field['validation']['pattern_message'] = __( 'Please enter full-width kana characters.', 'form-plant' );
					break;

				case 'between':
					if ( is_array( $rule_value ) ) {
						if ( isset( $rule_value['min'] ) && '' !== $rule_value['min'] ) {
							$field['validation']['min_length'] = (int) $rule_value['min'];
						}
						if ( isset( $rule_value['max'] ) && '' !== $rule_value['max'] ) {
							$field['validation']['max_length'] = (int) $rule_value['max'];
						}
					}
					break;

				case 'minlength':
					if ( is_array( $rule_value ) && isset( $rule_value['length'] ) ) {
						$field['validation']['min_length'] = (int) $rule_value['length'];
					} elseif ( ! is_array( $rule_value ) ) {
						$field['validation']['min_length'] = (int) $rule_value;
					}
					break;

				case 'eq':
					if ( is_array( $rule_value ) && isset( $rule_value['equal_to'] ) ) {
						$value                                  = (string) $rule_value['equal_to'];
						$field['validation']['pattern']         = '/^' . preg_quote( $value, '/' ) . '$/';
						$field['validation']['pattern_message'] = sprintf(
							/* translators: %s: required value. */
							__( 'Please enter "%s".', 'form-plant' ),
							$value
						);
					}
					break;

				case 'filetype':
				case 'fileType':
					$types = '';
					if ( is_array( $rule_value ) && isset( $rule_value['types'] ) ) {
						$types = (string) $rule_value['types'];
					} elseif ( is_string( $rule_value ) ) {
						$types = $rule_value;
					}
					if ( '' !== $types ) {
						$field['allowed_types'] = array_values(
							array_filter(
								array_map( 'trim', explode( ',', $types ) )
							)
						);
					}
					break;

				case 'filesize':
				case 'fileSize':
				case 'maxfilesize':
				case 'maxFileSize':
					$bytes = 0;
					if ( is_array( $rule_value ) && isset( $rule_value['bytes'] ) ) {
						$bytes = (int) $rule_value['bytes'];
					} elseif ( is_numeric( $rule_value ) ) {
						$bytes = (int) $rule_value;
					}
					if ( $bytes > 0 ) {
						$mb                  = (int) max( 1, ceil( $bytes / ( 1024 * 1024 ) ) );
						$field['max_size']   = $mb;
					}
					break;

				case 'akismet':
				case 'akismet_check':
					$this->logger->add_warning(
						FPLANT_Migrator_Base::LEVEL_WARNING,
						'akismet_not_migrated',
						sprintf(
							/* translators: %s: target field name. */
							__( 'The Akismet setting ("%s") will not be migrated. Please configure reCAPTCHA / Turnstile in Form Plant separately.', 'form-plant' ),
							$target_original
						),
						array( 'target' => $target_original )
					);
					break;

				default:
					$this->logger->add_warning(
						FPLANT_Migrator_Base::LEVEL_INFO,
						'unknown_validation_rule',
						sprintf(
							/* translators: 1: rule key, 2: target field name. */
							__( 'Validation rule "%1$s" (for "%2$s") could not be migrated. Please reconfigure it manually.', 'form-plant' ),
							(string) $rule_key,
							$target_original
						),
						array( 'rule' => (string) $rule_key, 'target' => $target_original )
					);
					break;
			}
		}

		return $field;
	}
}
